name: skin_checker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.4.0+1
  badges: ^2.0.2
  easy_localization: ^3.0.0
  flutter_gen: ^4.1.6
  flutter_rating_bar: ^4.0.0
  image_picker: ^0.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/langs/
  fonts:
    - family: Black
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
    - family: Bold
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
    - family: ExtraBold
      fonts:
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
    - family: ExtraLight
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
    - family: Light
      fonts:
        - asset: assets/fonts/Tajawal-Light.ttf
    - family: Medium
      fonts:
        - asset: assets/fonts/Tajawal-Medium.ttf
    - family: Regular
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
